# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.16.2
_src_path: gh:tsvikas/python-template
format_tool: black
get_package_version_from_vcs: false
github_user: tsvikas
has_cli: true
in_codecov: true
in_pypi: false
in_rtd: false
jupyter_files: forbid
license: MIT
package_description: Get a commit message from ChatGPT, with emojies ✨.
package_name: vibes
project_name: vibes
python_min: 13
user_email: tsvikas@gmail.com
user_name: Tsvika Shapira
year: 2025
