[project]
name = "gitmoji-llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cyclopts>=3.7.0",
    "gitpython>=3.1.44",
]
